# Generated by Django 6.0.3 on 2026-03-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar_web', '0002_cajas_clientes_detallepedido_movimientoscaja_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categorias',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='mesas',
            table='mesas',
        ),
        migrations.AlterModelTable(
            name='pedidos',
            table='pedidos',
        ),
    ]
